### ISSUE TITLE
Wrong ID pairs for the «Shaman King 2021»

### ISSUE THREAD

**Issue by TopoR** [Atelier-Shiori/Hato#4]
Hi!
I guess it's not worth for a ticket, but anyway this small thing keep messing my lists. MAL to AniList = correct id pair, AniList to MAL = wrong one (**39565** instead of **42205**). Can you update this please? :)
(Also Kitsu to both MAL and AL is wrong for the «Shaman King 2021»).

**Comment by moyitpro** [comment]
I fixed this issue. Apparently, there were duplicate entries for AniList id 119675, one with the incorrect title ids for Kitsu and MyAnimeList. I deleted the duplicate entry. Make sure you click or tap the "Reset Mappings" option to clear all the entries stored in the app. It will fetch the correct mapping from the server.

I will have a web form allowing users to report incorrect mapping data soon.
